### PR TITLE
Updates for psc 0.9.1 and dependencies.

### PR DESCRIPTION
**Pull request by jasonzoladz**

### CODE REVIEW

**Comment by jasonzoladz** [comment]
As you know, the current Travis build is set up with an old version of `psc`.

**Comment by jdegoes** [comment]
Hi @jasonzoladz. Thanks for the PR. :)

Can you please update the Travis build, too?

**Comment by jasonzoladz** [comment]
Will do...  A good opportunity to learn Travis.  :)

**Comment by garyb** [comment]
Looks like it's still spitting out warnings in the build, could you fix those too please?

In fact, could you use this [`package.json`](https://github.com/slamdata/purescript-stalling-coroutines/blob/a2e8ba0b9afe573dab67fd394ec12f5a46f5a410/package.json) and this [`.travis.yml`](https://github.com/slamdata/purescript-stalling-coroutines/blob/a2e8ba0b9afe573dab67fd394ec12f5a46f5a410/.travis.yml) instead please? It will turn warnings into errors in the build, and also ensures we're not accidentally relying on dev dependencies for the library code.

**Comment by jasonzoladz** [comment]
Fixed warnings; updated `.travis.yml; however, couldn't get pulp to pass the `--strict` or `--censor-lib` flag on to `psc`, so I didn't alter `package.json`.

**Comment by garyb** [comment]
Those flags are for `purescript-psa`, which is one of the dependencies added in that `package.json` :smile:

**Comment by jasonzoladz** [comment]
Cool.  I'l try again.

**Comment by jasonzoladz** [comment]
Should be set now.  Thanks for the heads-up re: `purescript-psa`.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
